print('ola,Mundo')
print('chaves')
print('zayon')
print('presta')
print('atençao')
print('lasanha')
print('pizza')
print('strogonoff')
print('comida japonesa')
print('blood strike,mine,arena breakout e ff')
